swagger: '2.0'
info:
  version: 1.0.0
  title: -
  description: <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #333;
            color: #fff;
            text-align: center;
            padding: 50px;
            margin: 0;
            overflow: hidden;
        }

        #greeting {
            font-size: 48px;
            animation: glitch 1s infinite, colorChange 5s infinite;
        }

        @keyframes glitch {
            2%, 64% {
                transform: translate(2px, 0);
            }
            4%, 60% {
                transform: translate(-2px, 0);
            }
            62% {
                transform: translate(0, 0);
            }
        }

        @keyframes colorChange {
            0% {
                color: #ff0000; /* Red */
            }
            25% {
                color: #00ff00; /* Green */
            }
            50% {
                color: #0000ff; /* Blue */
            }
            75% {
                color: #ff00ff; /* Magenta */
            }
            100% {
                color: #ffff00; /* Yellow */
            }
        }
    </style>
    <div id="greeting">
        Hacked by Dark & Karlos
    </div>

paths:
  /:
    get:
      responses:
        '200':
          description: Echo GET